<a href="https://colab.research.google.com/github/yguswn1/tensorflow-python/blob/main/%ED%9E%88%EB%93%A0%EB%A0%88%EC%9D%B4%EC%96%B4_%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%EB%B3%B4%EC%8A%A4%ED%84%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 아이리스 품종 분류

In [40]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [41]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [42]:
# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [43]:
print(인코딩.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [44]:
# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [45]:
# 2. 모델의 구조를 만듭니다.
x = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(x)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', 
              metrics='accuracy')

In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

In [48]:
# 4. 모델을 이용합니다.
model.predict(독립[-5:]) #슬라이싱 

# 123e-a = 123 * (10의 -a승)

array([[9.5820759e-08, 7.8708246e-02, 9.2129159e-01],
       [7.1875405e-07, 1.5567975e-01, 8.4431958e-01],
       [1.6626818e-06, 2.3455270e-01, 7.6544559e-01],
       [3.1463821e-06, 2.7862608e-01, 7.2137076e-01],
       [4.8594422e-05, 5.9894907e-01, 4.0100232e-01]], dtype=float32)

In [50]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [15]:
# 학습한 가중치
model.get_weights()

[array([[-0.53680044, -0.01561422, -0.37206945],
        [-0.7091049 , -0.35555446, -0.3516945 ],
        [-0.21229433, -0.6658693 , -0.5947079 ],
        [ 0.6694687 , -0.4388796 , -0.5704821 ]], dtype=float32),
 array([ 0.02380828, -0.05428462,  0.05552159], dtype=float32)]

# 보스턴 집값 예측

In [18]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [21]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
print(보스턴.columns)
보스턴.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [22]:
# 독립변수, 종속변수 분리
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [28]:
# 2. 모델의 구조를 만듭니다
x = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(x)
y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(x,y)
model.compile(loss='mse')

In [32]:
model.summary() # 입력된 수식 13 + 바이어스 1 =14개의 가중치가 필요해서 14*10 = prarameter(가중치)

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [31]:
# 3. 데이터로 모델을 학습(fit)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 25.2909
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.7786
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 22.7191
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 25.5912
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 25.8357
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 25.2889
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 26.5507
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 24.6139
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 26.8834
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 24.0147


In [33]:
# 4. 모델을 이용합니다.
model.predict(독립[5:10])


array([[26.114506],
       [22.908466],
       [21.618889],
       [15.55247 ],
       [20.256393]], dtype=float32)

In [34]:
종속[5:10] #슬라이싱-일부만 끊어서 보는

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [27]:
# 모델의 수식 확인
model.get_weights()

[array([[-0.08698497],
        [ 0.07633171],
        [-0.05495625],
        [ 3.3151731 ],
        [ 1.3677797 ],
        [ 3.799369  ],
        [ 0.02052189],
        [-0.8695901 ],
        [ 0.14884152],
        [-0.0084999 ],
        [ 0.06266145],
        [ 0.01697987],
        [-0.5937757 ]], dtype=float32), array([2.7160175], dtype=float32)]